# Generated by Django 5.2 on 2025-08-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="name",
            field=models.CharField(
                choices=[
                    ("frontend", "Фронтенд"),
                    ("backend", "Бэкенд"),
                    ("testing", "Тестирование"),
                    ("management", "Управление проектами"),
                    ("design", "Дизайн"),
                    ("devops", "DevOps"),
                ],
                max_length=100,
                unique=True,
                verbose_name="Навык",
            ),
        ),
    ]
