# Generated by Django 5.2 on 2025-08-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="cover",
            field=models.ImageField(blank=True, upload_to="covers/"),
        ),
    ]
