# Generated by Django 5.2 on 2025-08-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_alter_skill_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employees",
            options={"verbose_name": "Сотрудник", "verbose_name_plural": "Сотрудники"},
        ),
        migrations.AlterModelOptions(
            name="employeeskill",
            options={
                "verbose_name": "Навык сотрудника",
                "verbose_name_plural": "Навыки сотрудников",
            },
        ),
        migrations.AlterModelOptions(
            name="skill",
            options={"verbose_name": "Навык", "verbose_name_plural": "Навыки"},
        ),
        migrations.AlterField(
            model_name="employees",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
        migrations.AlterField(
            model_name="employees",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="last name"
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="name",
            field=models.CharField(
                choices=[
                    ("frontend", "Фронтенд"),
                    ("backend", "Бэкенд"),
                    ("testing", "Тестирование"),
                    ("management", "Управление проектами"),
                    ("design", "Дизайн"),
                    ("devops", "DevOps"),
                ],
                max_length=100,
                unique=True,
            ),
        ),
    ]
