# Generated by Django 5.2 on 2025-08-19 12:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_employee_cover"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="cover",
        ),
        migrations.CreateModel(
            name="EmployeeImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        blank=True, upload_to="covers/", verbose_name="Изображение"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Чем меньше число, тем выше в галерее",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Порядковый номер",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Сотрудник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Галерея сотрудника",
                "verbose_name_plural": "Галереи сотрудников",
                "ordering": ("order", "created_at"),
                "unique_together": {("employee", "order")},
            },
        ),
    ]
