# Generated by Django 5.2 on 2025-08-19 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_remove_employee_cover_employeeimage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employeeimage",
            old_name="cover",
            new_name="image",
        ),
    ]
