# Generated by Django 5.2 on 2025-08-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "employees",
            "0003_alter_employee_options_alter_employeeskill_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeskill",
            name="skill",
            field=models.CharField(
                choices=[
                    ("frontend", "Фронтенд"),
                    ("backend", "Бэкенд"),
                    ("testing", "Тестирование"),
                    ("management", "Управление проектами"),
                    ("design", "Дизайн"),
                    ("devops", "DevOps"),
                ],
                max_length=100,
                verbose_name="Навык",
            ),
        ),
        migrations.DeleteModel(
            name="Skill",
        ),
    ]
