# Generated by Django 5.2 on 2025-08-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0004_alter_employeeskill_skill_delete_skill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="username",
            field=models.CharField(max_length=150, unique=True, verbose_name="Логин"),
        ),
    ]
