# Generated by Django 5.2 on 2025-08-19 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0004_rename_cover_employeeimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeimage",
            name="order",
            field=models.PositiveIntegerField(
                blank=True,
                default=None,
                help_text="Чем меньше число, тем выше в галерее",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Порядковый номер",
            ),
        ),
    ]
