# Generated by Django 5.2 on 2025-08-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0005_alter_employeeimage_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employeeimage",
            options={
                "ordering": ("order", "created_at"),
                "verbose_name": "файл сотрудника",
                "verbose_name_plural": "файлы сотрудников",
            },
        ),
        migrations.AddField(
            model_name="employeeimage",
            name="is_main",
            field=models.BooleanField(
                default=False,
                help_text="Использовать как главное фото сотрудника сотрудника",
                verbose_name="Главное фото",
            ),
        ),
    ]
