# Generated by Django 5.2 on 2025-08-13 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workplaces", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workplace",
            options={
                "verbose_name": "Рабочее место",
                "verbose_name_plural": "Рабочие места",
            },
        ),
    ]
