# Generated by Django 5.2 on 2025-08-19 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workplaces", "0002_alter_workplace_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workplace",
            old_name="employees",
            new_name="employee",
        ),
    ]
